### ISSUE TITLE
If another plugin removes the sign during a SignChangeEvent, SignEdit for Bukkit gets a `java.lang.ClassCastException`

### ISSUE THREAD

**Issue by Deltik** [Deltik/SignEdit#27]
When [BlockLocker](https://github.com/rutgerkok/BlockLocker) [removes a sign](https://github.com/rutgerkok/BlockLocker/blob/5f4f8603bb4f4b05a045991dd0929fc42548d8c1/src/main/java/nl/rutgerkok/blocklocker/impl/event/SignChangeListener.java#L56) edited by `/sign set …`, Bukkit sends a `SignChangeEvent` without a sign block.  This causes the following exception:

```
[18:10:29 INFO]: Deltik issued server command: /se 1 [Private]
[18:10:29 ERROR]: java.lang.ClassCastException: class org.bukkit.craftbukkit.v1_18_R1.block.CraftBlockState cannot be cast to class org.bukkit.block.Sign (org.bukkit.craftbukkit.v1_18_R1.block.CraftBlockState and org.bukkit.block.Sign are in unnamed module of loader java.net.URLClassLoader @5c29bfd)
        at SignEdit-1.13.6.jar//net.deltik.mc.signedit.integrations.StandardSignEditValidator.validate(StandardSignEditValidator.java:56)
        at SignEdit-1.13.6.jar//net.deltik.mc.signedit.integrations.StandardSignEditValidator.validate(StandardSignEditValidator.java:51)
        at SignEdit-1.13.6.jar//net.deltik.mc.signedit.SignText.applySign(SignText.java:85)
        at SignEdit-1.13.6.jar//net.deltik.mc.signedit.interactions.SetSignEditInteraction.interact(SetSignEditInteraction.java:50)
        at SignEdit-1.13.6.jar//net.deltik.mc.signedit.commands.SignCommand.onCommand(SignCommand.java:1133)
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.dispatchCommand(CraftServer.java:876)
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2268)
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2079)
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2060)
        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)
        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6)
        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:56)
        at net.minecraft.server.TickTask.run(TickTask.java:18)
        at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:149)
        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.c(IAsyncTaskHandlerReentrant.java:23)
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1413)
        at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:189)
        at net.minecraft.util.thread.IAsyncTaskHandler.y(IAsyncTaskHandler.java:122)
        at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1391)
        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1384)
        at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:132)
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1362)
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1268)
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by Deltik** [comment]
Fix looks like this:

![image](https://user-images.githubusercontent.com/1364268/146623675-cc776bcb-f167-4e8f-a077-de994162e225.png)
